title: harpoonLobotomy // BG3 Materials/Templates

author: harpoonLobotomy

description: Technical archaeology of Baldur’s Gate 3 - digging around in files, figuring out how to use them. With a specialisation in recreating materials in Blender, using their original nodegraphs blueprints.

url: "https://harpoonlobotomy.github.io"
baseurl: ""

theme: minima

minima:

  skin: solarized-light

  show_excerpts: true

  social_links:
    - title: Youtube
      icon: youtube
      url: "https://youtube.com/@harpoonlobotomy?si=ekZuphjm20mLuT42"

header_pages:
  - Scripts/lsmg_parsing/readme.md

show_downloads: false
google_analytics: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  