title: BG3 Forensics
description: Technical archaeology of Baldur’s Gate 3
url: "https://harpoonlobotomy.github.io"
baseurl: ""

collections:
  fieldnotes:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: fieldnotes
    values:
      layout: fieldnote

show_downloads: false
google_analytics: ""

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
