title: BG3 Forensics
description: Technical archaeology of Baldur’s Gate 3
url: "https://harpoonlobotomy.github.io"
baseurl: ""
theme: minima

collections:
  fieldnotes:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: fieldnotes
    values:
      layout: fieldnote

show_downloads: false
google_analytics: ""


